export const SET_USER_DETAILS = 'SET_USER_DETAILS'
// export const DOB = 'DOB'
// export const LANGUAGE = 'LANGUAGE'
// export const MOBILE_NUMBER = 'MOBILE_NUMBER'
// export const ADDRESS = 'ADDRESS'
// export const FILE_URI = 'FILE_URI'
